### ISSUE TITLE
Constant Crashing without Error

### ISSUE THREAD

**Issue by Abadima** [sleequid/tidalRPC#8]
It keeps on crashing everytime I try to use it, I'm unsure what the problem could be
![The Gif](https://i.gyazo.com/239224a87e80ea060cc55a145f391a7a.gif)

Any solution?

**Comment by ririxidev** [comment]
Hey, I'm sorry but I can't work on this RPC anymore. I dropped Tidal few days ago for Apple Music. Tidal is very misleading towards their customers & quality and I don't want to use their services anymore. I'm sorry.
Only thing that I can suggest you is checking in `eventvwr` (Event Viewer) why it's crashing.
